# Generated by Django 5.2.4 on 2025-08-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pubdate',
            new_name='pub_date',
        ),
    ]
